[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary
  postgresql-k8s/1 [executing] active: 
  postgresql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: 
  postgresql-k8s/1 [executing] waiting: Awaiting restart operation
  postgresql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.5    unsupported  01:49:30Z

App                       Version  Status  Scale  Charm                     Channel      Rev  Address         Exposed  Message
postgresql-k8s            14.13    active      3  postgresql-k8s                           0  10.152.183.62   no       
self-signed-certificates           active      1  self-signed-certificates  latest/edge  201  10.152.183.121  no       

Unit                         Workload  Agent  Address     Ports  Message
postgresql-k8s/0             active    idle   10.1.53.12         Primary
postgresql-k8s/1             active    idle   10.1.53.14         
postgresql-k8s/2*            active    idle   10.1.53.13         
self-signed-certificates/0*  active    idle   10.1.53.11         

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-postgresql-k8s-1: 01:40:04 ERROR unit.postgresql-k8s/1.juju-log certificates:3: Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-1: 01:40:06 ERROR unit.postgresql-k8s/1.juju-log Cannot push TLS certificates: <ops.pebble.ConnectionError ("Could not connect to Pebble: socket not found at '/charm/containers/postgresql/pebble.socket' (container restarted?)",)>
unit-postgresql-k8s-1: 01:41:25 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-0: 01:44:30 ERROR unit.postgresql-k8s/0.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...